const standard: string[] = [
  // Animals doing things
  "A cat wearing a top hat",
  "A dog driving a car",
  "A shark at a birthday party",
  "A penguin on a surfboard",
  "A dinosaur using a computer",
  "A frog on a lily pad with a crown",
  "A horse riding a human",
  "A bear doing yoga",
  "An octopus playing drums",
  "A sloth crossing a finish line",
  "A giraffe hiding behind a lamppost",
  "A snake wearing boots",
  "A pigeon carrying a briefcase",
  "A squirrel lifting weights",
  "A goldfish in a fishbowl on a rollercoaster",
  "An elephant in a bathtub",
  "A monkey painting a self-portrait",
  "A crab giving a thumbs up",
  "A chicken crossing a busy highway",
  "A duck in a raincoat",

  // People & characters
  "A ninja buying groceries",
  "A clown juggling cats",
  "A pirate with a parrot ordering coffee",
  "A caveman taking a selfie",
  "A wizard on a skateboard",
  "A cowboy riding a rocket",
  "A chef fighting a lobster",
  "A detective with a magnifying glass chasing a sock",
  "A robot walking a dog",
  "A ghost trying to high-five someone",
  "A vampire putting on sunscreen",
  "An astronaut floating with a pizza",
  "A knight fighting a rubber duck",
  "A grandma doing a kickflip",
  "A baby lifting a barbell",
  "A lumberjack at a tea party",
  "A sumo wrestler on a skateboard",
  "A mime trapped in an actual box",
  "A zombie at a job interview",
  "A santa on a motorcycle",

  // Scenes & situations
  "A cat and dog wedding",
  "A snowman in the desert",
  "A fish climbing a tree",
  "A car with legs instead of wheels",
  "A house on the moon",
  "A boat in the sky",
  "A tree growing pizza",
  "An upside-down city",
  "A submarine in a swimming pool",
  "A campfire underwater",
  "A traffic jam of animals",
  "A library full of screaming books",
  "A gym for vegetables",
  "A spa day for monsters",
  "A rock band of grandmas",

  // Food with personality
  "A sandwich running away from someone",
  "An angry pizza slice",
  "A taco wearing sunglasses",
  "A burger lifting weights",
  "Spaghetti in a wrestling match",
  "A donut being chased by a cop",
  "An avocado on a date",
  "A banana slipping on a banana peel",
  "A hotdog relaxing at the beach",
  "An egg skydiving",

  // Objects gone wild
  "A toaster launching toast into space",
  "A toilet as a throne",
  "An umbrella in a tornado",
  "A chair with muscles",
  "A pillow in a boxing ring",
  "A lamp afraid of the dark",
  "An alarm clock running away",
  "A shoe climbing a mountain",
  "A phone on fire",
  "A pencil drawing itself",

  // Mashups & absurd
  "Half penguin, half helicopter",
  "A bicycle made of spaghetti",
  "A volcano erupting candy",
  "A rainbow made of snakes",
  "A cloud raining tacos",
  "A tornado in a teacup",
  "A mountain wearing a hat",
  "The sun and moon arm wrestling",
  "A planet made of cheese",
  "A waterfall of chocolate",
];

const adultDirty: string[] = [
  // Awkward situations
  "A walk of shame in a dinosaur costume",
  "Someone stuck in a window sneaking out",
  "Two people fighting over the last slice of pizza at 3am",
  "A drunk person riding a shopping cart",
  "Someone crying in a club bathroom",
  "A couple arguing over IKEA furniture",
  "A drunk person vs. a vending machine",
  "Someone falling asleep in a weird place at a party",
  "A walk of shame past a church on Sunday",
  "A bouncer rejecting a clown from a nightclub",
  "Someone doing karaoke terribly",
  "A person tangled in Christmas lights at a party",
  "Two drunk people trying to cook ramen",
  "A hungover person at brunch",
  "Someone sneaking food into a movie theater badly",

  // Dating & romance gone wrong
  "A disastrous candlelit dinner",
  "Two people on the world's worst blind date",
  "Someone flexing in a bathroom mirror before a date",
  "A person bringing their mom on a date",
  "A love triangle at a bar",
  "Someone getting ghosted (literally, by a ghost)",
  "A terrible wedding proposal at a fast food restaurant",
  "Two exes running into each other at the gym",
  "A couple's yoga class going wrong",
  "Someone swiping on a dating app on the toilet",
  "A bachelor party on a school bus",
  "A bachelorette party at a retirement home",
  "Two people fighting over who pays the bill",
  "A breakup at IKEA",
  "Someone's Tinder photo vs. reality",

  // Party scenes
  "A house party where everything is on fire",
  "A beer pong tournament with grandparents",
  "Someone passed out with drawings on their face",
  "A frat house the morning after",
  "A pool party where nobody can swim",
  "A toga party at an office",
  "A costume party where two people wore the same outfit",
  "A rooftop party during an earthquake",
  "A rave in a retirement home",
  "Someone doing a keg stand in a suit",

  // Body humor
  "A butt tattoo reveal",
  "Someone flexing with noodle arms",
  "A spray tan gone horribly wrong",
  "Someone stuck in skinny jeans",
  "A wardrobe malfunction at a fancy event",
  "A bodybuilder who skipped leg day",
  "Someone with the world's worst sunburn",
  "A person covered in body glitter at the office",
  "Someone trying to wax themselves",
  "A terrible attempt at a sexy pose",

  // Adulting fails
  "A person's apartment vs. when guests come over",
  "Someone crying over their bank account",
  "A person eating cereal for dinner in formal wear",
  "Someone pretending to work while the boss walks by",
  "A person's fridge: expectation vs. reality",
  "Someone napping under their desk at work",
  "A person's laundry pile gaining sentience",
  "Someone having a breakdown at self-checkout",
  "A person microwaving something they shouldn't",
  "Someone calling in sick while clearly at the beach",

  // Night out chaos
  "A drunk person trying to parallel park",
  "Someone ordering everything on the menu at 2am",
  "A cab driver's face during a wild ride",
  "Someone losing a shoe on the dance floor",
  "A drunk person arguing with their reflection",
  "Someone trying to sneak into a VIP section",
  "A bartender's thousand-yard stare",
  "Two strangers bonding in a bar bathroom",
  "Someone dancing alone like nobody's watching (but everyone is)",
  "A drunk person explaining their business idea",

  // Miscellaneous
  "A walk of shame but make it fashion",
  "Someone hiding from their ex at a grocery store",
  "A hot tub time machine",
  "A gym selfie gone wrong",
  "Someone flirting terribly at a coffee shop",
  "A strip club for robots",
  "Someone trying to be sexy while eating wings",
  "A walk of shame on public transit",
  "Two people pretending not to know each other in public",
  "Someone's embarrassing search history as a painting",
  "A walk of shame during a parade",
  "A person trying to look cool and failing",
  "Someone getting caught talking to themselves",
  "A disastrous couple's costume",
  "Two people sharing one umbrella badly",
  "Someone trying to take a sexy selfie with a cat",
  "A person discovering a gray hair for the first time",
  "Someone eating a burrito the size of a baby",
  "A walk of shame but it's raining",
  "Someone aggressively eating cheese at 3am",
];

const familyFriendly: string[] = [
  // Cute animals
  "A kitten riding a unicorn",
  "A puppy playing in the snow",
  "A hamster driving a tiny car",
  "A bunny painting a picture",
  "A duckling wearing rain boots",
  "A baby elephant blowing bubbles",
  "A turtle wearing a rocket backpack",
  "A parrot reading a book",
  "A goldfish in a tiny submarine",
  "A butterfly wearing a top hat",
  "A ladybug carrying a tiny umbrella",
  "A baby panda on a slide",
  "A koala hugging a teddy bear",
  "An owl wearing glasses",
  "A dolphin jumping through a hoop",
  "A hedgehog in a hot air balloon",
  "A frog with a tiny crown on a lily pad",
  "A baby penguin ice skating",
  "A corgi in a spaceship",
  "A cat astronaut on the moon",

  // Fantasy & magic
  "A dragon roasting marshmallows",
  "A fairy building a treehouse",
  "A friendly monster reading bedtime stories",
  "A ghost blowing out birthday candles",
  "A unicorn at a lemonade stand",
  "A magic carpet stuck in traffic",
  "A genie popping out of a soda can",
  "A mermaid at a water park",
  "A troll guarding a candy bridge",
  "A wizard making pancakes",
  "A robot hugging a puppy",
  "A talking tree wearing a scarf",
  "A cloud raining candy",
  "A rainbow slide from sky to ground",
  "A castle made of pillows and blankets",
  "A yeti having a snowball fight",
  "A giant friendly spider knitting a web hammock",
  "A leprechaun on a pogo stick",
  "A phoenix roasting a hot dog",
  "A centaur playing basketball",

  // Silly scenes
  "A school bus flying through space",
  "A treehouse with an elevator",
  "A swimming pool full of jello",
  "A playground on the moon",
  "A snowman surfing",
  "A house made of candy",
  "A bicycle with square wheels",
  "A rocket ship made of cardboard boxes",
  "A dinosaur at a tea party",
  "A penguin delivering mail",
  "Animals having a talent show",
  "A fish riding a bicycle",
  "A caterpillar wearing tiny shoes on every foot",
  "An ant carrying a watermelon",
  "A snail racing a cheetah",

  // Food fun
  "A cupcake with a cape",
  "An ice cream cone melting in the sun crying",
  "A pizza that can fly",
  "A cookie building a gingerbread house",
  "A banana in pajamas",
  "A sandwich as tall as a skyscraper",
  "A donut rolling down a hill",
  "A bowl of cereal swimming",
  "A peanut butter jar hugging a jelly jar",
  "A watermelon at the beach",

  // Adventures
  "A pirate ship sailing through clouds",
  "A submarine exploring a bathtub",
  "A treasure chest full of toys",
  "A safari in a living room",
  "A treasure map drawn by a cat",
  "An explorer discovering a chocolate river",
  "A hot air balloon shaped like a panda",
  "A spaceship landing in a backyard",
  "A jungle gym made of rainbow",
  "A raft made of popsicle sticks",

  // Everyday silliness
  "A dog walking a human on a leash",
  "A cat in a superhero cape",
  "A teddy bear having a picnic",
  "A sock puppet show",
  "A crayon drawing itself",
  "A snowball fight between snowmen",
  "A pillow fort with a drawbridge",
  "A rubber duck leading a bath army",
  "A kite flying a person",
  "A yo-yo that won't come back",

  // Holidays
  "Santa on a surfboard",
  "The Easter Bunny lifting weights",
  "A jack-o'-lantern with a silly face",
  "A snowman building a human out of snow",
  "A birthday cake with too many candles",
  "A turkey in disguise",
  "A reindeer with a jetpack",
  "A trick-or-treater in a box costume",
  "A stocking stuffed with a puppy",
  "Fireworks shaped like animals",
];

export { standard, adultDirty, familyFriendly };
